name: Vulkan Wrapper Build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Escolha o tipo de build'
        required: true
        default: 'release'
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3 python3-pip python3-setuptools python3-venv python3-dev python3-wheel python3-mako \
            git ninja-build meson clang pkg-config \
            libx11-dev libxcb1-dev xorg-dev glslang-tools \
            libclc-20-dev libglvnd-dev libudev-dev spirv-llvm-translator-18-dev

      - name: Upgrade pip and Meson
        run: |
          python3 -m pip install --upgrade pip
          pip install --upgrade meson

      - name: Create build directory
        run: mkdir -p build

      - name: Configure build
        run: meson setup build . --buildtype=${{ github.event.inputs.build_type || 'release' }}

      - name: Build
        run: ninja -C build

      - name: Install
        run: sudo ninja -C build install

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vulkan-wrapper-build
          path: build/
